require "utils.globals"
require "config.base"
require "config.highlights"
require "config.maps"
require "config.lazy"
require "config.autocmds"
require "config.settings"

require "internal.cursorword"
require "lsp.config"
require "lsp.setup"
require "lsp.functions"
