#!/usr/bin/env bash

set -euo pipefail

##? Setups the neovim environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the neovim conf installer!"
echo "-------------------------------------------------"
echo

export NV_CFG="$HOME/.config/nvim"

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

git clone https://github.com/jvegaf/nvconf.git "$NV_CFG"

sh nvim +PackerSync